package com.patrick_crane.web.dto.event;

public enum EventType {

  SUBSCRIPTION_ORDER,
  SUBSCRIPTION_CHANGE,
  SUBSCRIPTION_CANCEL,
  SUBSCRIPTION_NOTICE,
  USER_ASSIGNMENT,
  USER_UNASSIGNMENT,
  USER_UPDATED,
  ADDON_ORDER,
  ADDON_CANCEL;

}
